/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import sims.model.Student;

/**
 *
 * @author Jireh
 */
public class CogReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form CogReportPanel
     *
     * @param student
     */
    public CogReportPanel(Student student) {
        initComponents();

        // STUDENT INFO
        String firstName = student.getEmail().getFirstName();
        String middleName = student.getMiddleName();
        String lastName = student.getEmail().getLastName();

        StudentFullName.setText("%s %s %s".formatted(student.getEmail().getFirstName(),
                student.getMiddleName() == null ? "" : String.valueOf(student.getMiddleName().charAt(0)) + ".",
                student.getEmail().getLastName()));
        StudentYearLevel.setText(student.getYearLevel());
        StudentNumber.setText(student.getStudentNumber());

        String sem = student.getCurrentSem();
        if (sem.equals("1")) {
            sem += "st ";
        } else {
            sem += "nd ";
        }

        AcademicYear.setText(sem + "2022-2023");

        int totalSubjects = 0,totalCredits = 0;
        double grade = 0,studentGPA = 0;
        //Insertion Method 
        for (var subject : student.getSubjects()) {
            totalSubjects++;
            totalCredits += Integer.parseInt(subject.getUnits());
            grade += subject.getGrade();
            
            // COURSE CODE
            var courseCodeLabel = labelGenerator(subject.getSubjectCode());
            CourseCodeColumn.add(courseCodeLabel);

            // COURSE TITLE
            var courseDescLabel = labelGenerator(subject.getSubjectTitle());
            CourseTitleColumn.add(courseDescLabel);

            // UNIT
            var unitLabel = labelGenerator(subject.getUnits());
            UnitColumn.add(unitLabel);

            // GRADE
            var gradeLabel = labelGenerator(Double.toString(subject.getGrade()));
            GradeColumn.add(gradeLabel);

            // REMARKS
            var remarks = subject.getRemarks();
            if (remarks == null) {
                remarks = "N/A";
            }

            var remarksLabel = labelGenerator(remarks);
            RemarksColumn.add(remarksLabel);

            // FACULTY
            var facultyLabel = labelGenerator(subject.getFaculty());
            FacultyColumn.add(facultyLabel);
        }
        studentGPA = grade / totalSubjects;
        
        TotalSubjectsEnrolled.setText(String.valueOf(totalSubjects));
        TotalCreditsEnrolled.setText(String.valueOf(totalCredits));
        TotalCreditsEarned.setText(String.valueOf(totalCredits));
        GPA.setText(Double.toString(studentGPA));

    }

    private JLabel labelGenerator(String content) {
        var label = new JLabel(content, SwingConstants.CENTER);
        label.setFont(new Font("JetBrains Mono", Font.PLAIN, 14));

        return label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        StudentFullName = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        StudentYearLevel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        StudentNumber = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        AcademicYear = new javax.swing.JLabel();
        MainContentSection = new javax.swing.JPanel();
        TableHeaders = new javax.swing.JPanel();
        CCLabel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CTLabel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ULabel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        GLabel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        RLabel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        FLabel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TableColumns = new javax.swing.JPanel();
        CourseCodeColumn = new javax.swing.JPanel();
        CourseTitleColumn = new javax.swing.JPanel();
        UnitColumn = new javax.swing.JPanel();
        GradeColumn = new javax.swing.JPanel();
        RemarksColumn = new javax.swing.JPanel();
        FacultyColumn = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        TotalInformation = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        TotalSubjectsEnrolled = new javax.swing.JLabel();
        TotalCreditsEnrolled = new javax.swing.JLabel();
        TotalCreditsEarned = new javax.swing.JLabel();
        GPA = new javax.swing.JLabel();
        GradingSystemSection = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1006, 720));
        setLayout(null);

        Container.setPreferredSize(new java.awt.Dimension(1006, 720));
        Container.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        Header.setPreferredSize(new java.awt.Dimension(1006, 180));
        Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(250, 180));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sims/assets/cvsu-logo-mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel77)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        Header.add(jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(506, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel6.setPreferredSize(new java.awt.Dimension(506, 50));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CVSU Bacoor Campus");
        jPanel6.add(jLabel1);

        jPanel4.add(jPanel6);

        jPanel3.setPreferredSize(new java.awt.Dimension(506, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Certificate of Grades");
        jPanel3.add(jLabel2);

        jPanel4.add(jPanel3);

        Header.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Header.add(jPanel5);

        jPanel7.setPreferredSize(new java.awt.Dimension(1006, 80));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel9.setPreferredSize(new java.awt.Dimension(915, 80));
        jPanel9.setLayout(new java.awt.GridLayout(0, 2));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel12.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("Fullname:");
        jPanel12.add(jLabel3);

        jPanel10.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(287, 40));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        StudentFullName.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        StudentFullName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentFullName.setText("Jireh Alny T. Tumbagahan");
        jPanel13.add(StudentFullName);

        jPanel10.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Year Level:");
        jPanel14.add(jLabel5);

        jPanel10.add(jPanel14);

        jPanel15.setPreferredSize(new java.awt.Dimension(287, 40));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        StudentYearLevel.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        StudentYearLevel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentYearLevel.setText("Third Year");
        jPanel15.add(StudentYearLevel);

        jPanel10.add(jPanel15);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        jPanel16.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel7.setText("Student Number:");
        jPanel16.add(jLabel7);

        jPanel11.add(jPanel16);

        jPanel17.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        StudentNumber.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        StudentNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentNumber.setText("202110838");
        jPanel17.add(StudentNumber);

        jPanel11.add(jPanel17);

        jPanel18.setPreferredSize(new java.awt.Dimension(170, 40));
        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel9.setText("Academic Year:");
        jPanel18.add(jLabel9);

        jPanel11.add(jPanel18);

        jPanel19.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        AcademicYear.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        AcademicYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AcademicYear.setText("2ND SEM. YEAR-YEAR");
        jPanel19.add(AcademicYear);

        jPanel11.add(jPanel19);

        jPanel9.add(jPanel11);

        jPanel7.add(jPanel9);

        Header.add(jPanel7);

        Container.add(Header);

        MainContentSection.setPreferredSize(new java.awt.Dimension(1006, 310));
        MainContentSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        TableHeaders.setPreferredSize(new java.awt.Dimension(915, 40));
        TableHeaders.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        CCLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        CCLabel.setPreferredSize(new java.awt.Dimension(106, 40));
        CCLabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Course Code");
        CCLabel.add(jLabel11);

        TableHeaders.add(CCLabel);

        CTLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CTLabel.setPreferredSize(new java.awt.Dimension(385, 40));
        CTLabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Course Title");
        CTLabel.add(jLabel12);

        TableHeaders.add(CTLabel);

        ULabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        ULabel.setPreferredSize(new java.awt.Dimension(66, 40));
        ULabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Unit");
        ULabel.add(jLabel13);

        TableHeaders.add(ULabel);

        GLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        GLabel.setPreferredSize(new java.awt.Dimension(106, 40));
        GLabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel14.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Grade");
        GLabel.add(jLabel14);

        TableHeaders.add(GLabel);

        RLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        RLabel.setPreferredSize(new java.awt.Dimension(106, 40));
        RLabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel15.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Remarks");
        RLabel.add(jLabel15);

        TableHeaders.add(RLabel);

        FLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FLabel.setPreferredSize(new java.awt.Dimension(146, 40));
        FLabel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Faculty");
        FLabel.add(jLabel16);

        TableHeaders.add(FLabel);

        MainContentSection.add(TableHeaders);

        TableColumns.setPreferredSize(new java.awt.Dimension(915, 270));
        TableColumns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        CourseCodeColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        CourseCodeColumn.setPreferredSize(new java.awt.Dimension(106, 270));
        CourseCodeColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(CourseCodeColumn);

        CourseTitleColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        CourseTitleColumn.setPreferredSize(new java.awt.Dimension(385, 270));
        CourseTitleColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(CourseTitleColumn);

        UnitColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        UnitColumn.setPreferredSize(new java.awt.Dimension(66, 270));
        UnitColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(UnitColumn);

        GradeColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        GradeColumn.setPreferredSize(new java.awt.Dimension(106, 270));
        GradeColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(GradeColumn);

        RemarksColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        RemarksColumn.setPreferredSize(new java.awt.Dimension(106, 270));
        RemarksColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(RemarksColumn);

        FacultyColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        FacultyColumn.setPreferredSize(new java.awt.Dimension(146, 270));
        FacultyColumn.setLayout(new java.awt.GridLayout(10, 1));
        TableColumns.add(FacultyColumn);

        MainContentSection.add(TableColumns);

        Container.add(MainContentSection);

        jPanel22.setPreferredSize(new java.awt.Dimension(1006, 6));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        Container.add(jPanel22);

        Footer.setPreferredSize(new java.awt.Dimension(1006, 215));
        Footer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        TotalInformation.setOpaque(false);
        TotalInformation.setPreferredSize(new java.awt.Dimension(915, 90));
        TotalInformation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel21.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel21.setLayout(new java.awt.GridLayout(4, 1));

        jLabel18.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel18.setText("Total Subjects Enrolled");
        jPanel21.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel19.setText("Total Credits Enrolled");
        jPanel21.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel20.setText("Total Credits Earned");
        jPanel21.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel21.setText("Grade Point Average");
        jPanel21.add(jLabel21);

        TotalInformation.add(jPanel21);

        jPanel32.setPreferredSize(new java.awt.Dimension(40, 90));
        jPanel32.setLayout(new java.awt.GridLayout(4, 1));

        jLabel69.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel69.setText(":");
        jPanel32.add(jLabel69);

        jLabel70.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel70.setText(":");
        jPanel32.add(jLabel70);

        jLabel71.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel71.setText(":");
        jPanel32.add(jLabel71);

        jLabel72.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel72.setText(":");
        jPanel32.add(jLabel72);

        TotalInformation.add(jPanel32);

        jPanel33.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel33.setLayout(new java.awt.GridLayout(4, 1));

        TotalSubjectsEnrolled.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        TotalSubjectsEnrolled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalSubjectsEnrolled.setText("6");
        jPanel33.add(TotalSubjectsEnrolled);

        TotalCreditsEnrolled.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        TotalCreditsEnrolled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalCreditsEnrolled.setText("23");
        jPanel33.add(TotalCreditsEnrolled);

        TotalCreditsEarned.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        TotalCreditsEarned.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalCreditsEarned.setText("24");
        jPanel33.add(TotalCreditsEarned);

        GPA.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        GPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GPA.setText("1.65");
        jPanel33.add(GPA);

        TotalInformation.add(jPanel33);

        Footer.add(TotalInformation);

        GradingSystemSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GradingSystemSection.setPreferredSize(new java.awt.Dimension(915, 125));
        GradingSystemSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel20.setPreferredSize(new java.awt.Dimension(455, 123));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel24.setPreferredSize(new java.awt.Dimension(70, 123));
        jPanel24.setLayout(new java.awt.GridLayout(6, 1));

        jLabel17.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("1.00");
        jPanel24.add(jLabel17);

        jLabel22.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1.25");
        jPanel24.add(jLabel22);

        jLabel23.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("1.50");
        jPanel24.add(jLabel23);

        jLabel24.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("1.75");
        jPanel24.add(jLabel24);

        jLabel25.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("2.00");
        jPanel24.add(jLabel25);

        jLabel26.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("2.25");
        jPanel24.add(jLabel26);

        jPanel20.add(jPanel24);

        jPanel26.setPreferredSize(new java.awt.Dimension(130, 123));
        jPanel26.setLayout(new java.awt.GridLayout(6, 1));

        jLabel28.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Marked Excellent");
        jPanel26.add(jLabel28);

        jLabel34.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Excellent ");
        jPanel26.add(jLabel34);

        jLabel35.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Very Superior");
        jPanel26.add(jLabel35);

        jLabel36.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Superior");
        jPanel26.add(jLabel36);

        jLabel37.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Very Good");
        jPanel26.add(jLabel37);

        jLabel38.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Good");
        jPanel26.add(jLabel38);

        jPanel20.add(jPanel26);

        jPanel27.setPreferredSize(new java.awt.Dimension(20, 123));
        jPanel27.setLayout(new java.awt.GridLayout(6, 1));

        jLabel39.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("=");
        jPanel27.add(jLabel39);

        jLabel40.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("=");
        jPanel27.add(jLabel40);

        jLabel41.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("=");
        jPanel27.add(jLabel41);

        jLabel42.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("=");
        jPanel27.add(jLabel42);

        jLabel43.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("=");
        jPanel27.add(jLabel43);

        jLabel44.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("=");
        jPanel27.add(jLabel44);

        jPanel20.add(jPanel27);

        jPanel28.setPreferredSize(new java.awt.Dimension(120, 123));
        jPanel28.setLayout(new java.awt.GridLayout(6, 1));

        jLabel45.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("96.7 - 100");
        jPanel28.add(jLabel45);

        jLabel46.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("93.4 - 96.6");
        jPanel28.add(jLabel46);

        jLabel47.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("90.01 - 93.3");
        jPanel28.add(jLabel47);

        jLabel48.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("86.70 - 90.0");
        jPanel28.add(jLabel48);

        jLabel49.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("83.4 - 86.6");
        jPanel28.add(jLabel49);

        jLabel50.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("80.01 - 83.3");
        jPanel28.add(jLabel50);

        jPanel20.add(jPanel28);

        GradingSystemSection.add(jPanel20);

        jPanel23.setPreferredSize(new java.awt.Dimension(455, 123));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jPanel25.setPreferredSize(new java.awt.Dimension(70, 123));
        jPanel25.setLayout(new java.awt.GridLayout(6, 1));

        jLabel27.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("2.50");
        jPanel25.add(jLabel27);

        jLabel29.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("3.00");
        jPanel25.add(jLabel29);

        jLabel30.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("4.00");
        jPanel25.add(jLabel30);

        jLabel31.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("5.00");
        jPanel25.add(jLabel31);

        jLabel32.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("INC");
        jPanel25.add(jLabel32);

        jLabel33.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("DRP");
        jPanel25.add(jLabel33);

        jPanel23.add(jPanel25);

        jPanel29.setPreferredSize(new java.awt.Dimension(155, 123));
        jPanel29.setLayout(new java.awt.GridLayout(6, 1));

        jLabel51.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("Satisfactory");
        jPanel29.add(jLabel51);

        jLabel52.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("Passed");
        jPanel29.add(jLabel52);

        jLabel53.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Conditional Failure");
        jPanel29.add(jLabel53);

        jLabel54.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel54.setText("Failed");
        jPanel29.add(jLabel54);

        jLabel55.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("Incomplete");
        jPanel29.add(jLabel55);

        jLabel56.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel56.setText("Dropped Subject");
        jPanel29.add(jLabel56);

        jPanel23.add(jPanel29);

        jPanel31.setPreferredSize(new java.awt.Dimension(20, 123));
        jPanel31.setLayout(new java.awt.GridLayout(6, 1));

        jLabel63.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("=");
        jPanel31.add(jLabel63);

        jLabel64.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("=");
        jPanel31.add(jLabel64);

        jLabel65.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel65.setText("=");
        jPanel31.add(jLabel65);

        jLabel66.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel66.setText("=");
        jPanel31.add(jLabel66);

        jLabel67.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel67.setText("=");
        jPanel31.add(jLabel67);

        jLabel68.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel68.setText("=");
        jPanel31.add(jLabel68);

        jPanel23.add(jPanel31);

        jPanel30.setPreferredSize(new java.awt.Dimension(120, 123));
        jPanel30.setLayout(new java.awt.GridLayout(6, 1));

        jLabel57.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("76.7 - 80.0");
        jPanel30.add(jLabel57);

        jLabel58.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("70.0 - 73.3");
        jPanel30.add(jLabel58);

        jLabel59.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("50.0 - 69.99");
        jPanel30.add(jLabel59);

        jLabel60.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Below 50");
        jPanel30.add(jLabel60);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel30.add(jLabel61);

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel30.add(jLabel62);

        jPanel23.add(jPanel30);

        GradingSystemSection.add(jPanel23);

        Footer.add(GradingSystemSection);

        Container.add(Footer);

        add(Container);
        Container.setBounds(0, 0, 1010, 720);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcademicYear;
    private javax.swing.JPanel CCLabel;
    private javax.swing.JPanel CTLabel;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel CourseCodeColumn;
    private javax.swing.JPanel CourseTitleColumn;
    private javax.swing.JPanel FLabel;
    private javax.swing.JPanel FacultyColumn;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel GLabel;
    private javax.swing.JLabel GPA;
    private javax.swing.JPanel GradeColumn;
    private javax.swing.JPanel GradingSystemSection;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel MainContentSection;
    private javax.swing.JPanel RLabel;
    private javax.swing.JPanel RemarksColumn;
    private javax.swing.JLabel StudentFullName;
    private javax.swing.JLabel StudentNumber;
    private javax.swing.JLabel StudentYearLevel;
    private javax.swing.JPanel TableColumns;
    private javax.swing.JPanel TableHeaders;
    private javax.swing.JLabel TotalCreditsEarned;
    private javax.swing.JLabel TotalCreditsEnrolled;
    private javax.swing.JPanel TotalInformation;
    private javax.swing.JLabel TotalSubjectsEnrolled;
    private javax.swing.JPanel ULabel;
    private javax.swing.JPanel UnitColumn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
