/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import sims.model.Colors;
import sims.model.Student;

/**
 *
 * @author Jireh
 */
public class CoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form CoursePanel
     *
     * @param student
     */
    public CoursePanel(Student student) {
        initComponents();

        int totalUnits = 0;

        for (var subject : student.getSubjects()) {
            // COURSE CODE
            var subjectCourseCodeLabel = labelGenerator(subject.getSubjectCode());
            var subjectCourseCodePanel = new JPanel();
            subjectCourseCodePanel.add(subjectCourseCodeLabel);
            subjectCourseCodePanel.setLayout(new GridLayout());
            subjectCourseCodePanel.setBackground(Colors.PRIMARY_COLOR);
            subjectCourseCodePanel.setPreferredSize(new Dimension(250, 50));

            CourseCodeColumn.add(subjectCourseCodePanel);

            // COURSE DESCRIPTION
            var subjectCourseDescLabel = labelGenerator(subject.getSubjectTitle());
            subjectCourseDescLabel.setFont(new Font("JetBrains Mono", Font.PLAIN, 12));
            JPanel subjectCourseDescPanel = new JPanel();
            subjectCourseDescPanel.add(subjectCourseDescLabel);
            subjectCourseDescPanel.setLayout(new GridLayout());
            subjectCourseDescPanel.setBackground(Colors.PRIMARY_COLOR);
            subjectCourseDescPanel.setPreferredSize(new Dimension(420, 50));

            CourseDescriptionColumn.add(subjectCourseDescPanel);

            // UNITS
            var subjectCourseUnitsLabel = labelGenerator(subject.getUnits());
            var subjectCourseUnitsPanel = new JPanel();
            subjectCourseUnitsPanel.add(subjectCourseUnitsLabel);
            subjectCourseUnitsPanel.setLayout(new GridLayout());
            subjectCourseUnitsPanel.setBackground(Colors.PRIMARY_COLOR);
            subjectCourseUnitsPanel.setPreferredSize(new Dimension(150, 50));
            totalUnits += Integer.parseInt(subject.getUnits());
            CourseUnitColumn.add(subjectCourseUnitsPanel);

            // SECTION
            var subjectCourseSectionLabel = labelGenerator(student.getYearLevel() + "-" + student.getSection());
            var subjectCourseSectionPanel = new JPanel();
            subjectCourseSectionPanel.add(subjectCourseSectionLabel);
            subjectCourseSectionPanel.setLayout(new GridLayout());
            subjectCourseSectionPanel.setBackground(Colors.PRIMARY_COLOR);
            subjectCourseSectionPanel.setPreferredSize(new Dimension(186, 50));

            CourseSectionColumn.add(subjectCourseSectionPanel);
            /*
                Size Formats for column
                CourseCodeColumn - Width: 250, Height: 50
                CourseDescriptionColumn - Width: 420, Height: 50
                CourseUnitColumn - Width: 150, Height: 50
                CourseSectionColumn - Width: 186, Height: 50
             */
        }

        // TOTAL UNITS
        var totalUnitsLabel = labelGenerator("Total: " + String.valueOf(totalUnits));
        var totalUnitsPanel = new JPanel();
        totalUnitsPanel.add(totalUnitsLabel);
        totalUnitsPanel.setLayout(new GridLayout());
        totalUnitsPanel.setBackground(Colors.PRIMARY_COLOR);
        totalUnitsPanel.setPreferredSize(new Dimension(150, 50));
        CourseUnitColumn.add(totalUnitsPanel);
    }

    private JLabel labelGenerator(String content) {
        JLabel label = new JLabel(content);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setVerticalAlignment(SwingConstants.CENTER);
        label.setFont(new Font("JetBrains Mono", Font.PLAIN, 24));

        return label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CourseCodeColumn = new javax.swing.JPanel();
        CourseCodeHeaderPanel = new javax.swing.JPanel();
        CourseCodeHeaderLabel = new javax.swing.JLabel();
        CourseDescriptionColumn = new javax.swing.JPanel();
        CourseDescriptionHeaderPanel = new javax.swing.JPanel();
        CourseDescriptionHeaderLabel = new javax.swing.JLabel();
        CourseUnitColumn = new javax.swing.JPanel();
        CourseUnitHeaderPanel = new javax.swing.JPanel();
        CourseUnitHeaderLabel = new javax.swing.JLabel();
        CourseSectionColumn = new javax.swing.JPanel();
        CourseSectionHeaderPanel = new javax.swing.JPanel();
        CourseSectionHeaderLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(1006, 720));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        CourseCodeColumn.setBackground(new java.awt.Color(217, 217, 217));
        CourseCodeColumn.setPreferredSize(new java.awt.Dimension(250, 720));
        CourseCodeColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        CourseCodeHeaderPanel.setBackground(new java.awt.Color(205, 205, 205));
        CourseCodeHeaderPanel.setMinimumSize(new java.awt.Dimension(100, 80));
        CourseCodeHeaderPanel.setPreferredSize(new java.awt.Dimension(250, 70));
        CourseCodeHeaderPanel.setLayout(new java.awt.GridLayout(1, 0));

        CourseCodeHeaderLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        CourseCodeHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseCodeHeaderLabel.setText("Course Code");
        CourseCodeHeaderPanel.add(CourseCodeHeaderLabel);

        CourseCodeColumn.add(CourseCodeHeaderPanel);

        jPanel1.add(CourseCodeColumn);

        CourseDescriptionColumn.setBackground(new java.awt.Color(217, 217, 217));
        CourseDescriptionColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(205, 205, 205)));
        CourseDescriptionColumn.setPreferredSize(new java.awt.Dimension(420, 720));
        CourseDescriptionColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        CourseDescriptionHeaderPanel.setBackground(new java.awt.Color(205, 205, 205));
        CourseDescriptionHeaderPanel.setMinimumSize(new java.awt.Dimension(100, 80));
        CourseDescriptionHeaderPanel.setPreferredSize(new java.awt.Dimension(420, 70));
        CourseDescriptionHeaderPanel.setLayout(new java.awt.GridLayout(1, 0));

        CourseDescriptionHeaderLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        CourseDescriptionHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseDescriptionHeaderLabel.setText("Course Description");
        CourseDescriptionHeaderPanel.add(CourseDescriptionHeaderLabel);

        CourseDescriptionColumn.add(CourseDescriptionHeaderPanel);

        jPanel1.add(CourseDescriptionColumn);

        CourseUnitColumn.setBackground(new java.awt.Color(217, 217, 217));
        CourseUnitColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(205, 205, 205)));
        CourseUnitColumn.setPreferredSize(new java.awt.Dimension(150, 720));
        CourseUnitColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        CourseUnitHeaderPanel.setBackground(new java.awt.Color(205, 205, 205));
        CourseUnitHeaderPanel.setMinimumSize(new java.awt.Dimension(100, 80));
        CourseUnitHeaderPanel.setPreferredSize(new java.awt.Dimension(250, 70));
        CourseUnitHeaderPanel.setLayout(new java.awt.GridLayout(1, 0));

        CourseUnitHeaderLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        CourseUnitHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseUnitHeaderLabel.setText("Unit");
        CourseUnitHeaderPanel.add(CourseUnitHeaderLabel);

        CourseUnitColumn.add(CourseUnitHeaderPanel);

        jPanel1.add(CourseUnitColumn);

        CourseSectionColumn.setBackground(new java.awt.Color(217, 217, 217));
        CourseSectionColumn.setPreferredSize(new java.awt.Dimension(186, 720));
        CourseSectionColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        CourseSectionHeaderPanel.setBackground(new java.awt.Color(205, 205, 205));
        CourseSectionHeaderPanel.setMinimumSize(new java.awt.Dimension(100, 80));
        CourseSectionHeaderPanel.setPreferredSize(new java.awt.Dimension(250, 70));
        CourseSectionHeaderPanel.setLayout(new java.awt.GridLayout(1, 0));

        CourseSectionHeaderLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        CourseSectionHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseSectionHeaderLabel.setText("Section");
        CourseSectionHeaderPanel.add(CourseSectionHeaderLabel);

        CourseSectionColumn.add(CourseSectionHeaderPanel);

        jPanel1.add(CourseSectionColumn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseCodeColumn;
    private javax.swing.JLabel CourseCodeHeaderLabel;
    private javax.swing.JPanel CourseCodeHeaderPanel;
    private javax.swing.JPanel CourseDescriptionColumn;
    private javax.swing.JLabel CourseDescriptionHeaderLabel;
    private javax.swing.JPanel CourseDescriptionHeaderPanel;
    private javax.swing.JPanel CourseSectionColumn;
    private javax.swing.JLabel CourseSectionHeaderLabel;
    private javax.swing.JPanel CourseSectionHeaderPanel;
    private javax.swing.JPanel CourseUnitColumn;
    private javax.swing.JLabel CourseUnitHeaderLabel;
    private javax.swing.JPanel CourseUnitHeaderPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
