/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import sims.model.Student;

/**
 *
 * @author johnc
 */
public class LandingPanel extends javax.swing.JPanel {

    /**
     * Creates new form LandingPanel
     * @param student
     */
    public LandingPanel(Student student) {
        initComponents();
        welcomeNameLabel.setText("%s %s!".formatted(student.getEmail().getFirstName(),student.getEmail().getLastName()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTagLabel = new javax.swing.JLabel();
        welcomeNameLabel = new javax.swing.JLabel();
        welcomeImageLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeTagLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 48)); // NOI18N
        welcomeTagLabel.setText("Welcome,");
        add(welcomeTagLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        welcomeNameLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 48)); // NOI18N
        welcomeNameLabel.setText("Arvie Fabila");
        add(welcomeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 640, -1));

        welcomeImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sims/assets/welcomeBG-640x426.jpg"))); // NOI18N
        add(welcomeImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel welcomeImageLabel;
    private javax.swing.JLabel welcomeNameLabel;
    private javax.swing.JLabel welcomeTagLabel;
    // End of variables declaration//GEN-END:variables
}
