/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Jireh
 */
public class PayFeesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayFeesPanel
     */
    public PayFeesPanel() {
        initComponents();
        
        LinkedList<String> subjectList = new LinkedList();
        subjectList.add("ITEC - 25");
        subjectList.add("FITT - 4");
        subjectList.add("FITT - 3");
        subjectList.add("FITT - 2");
        subjectList.add("FITT - 1");
        
        for(String subject : subjectList){
            JLabel label = new JLabel(subject);
            label.setHorizontalAlignment(SwingConstants.CENTER);
            label.setVerticalAlignment(SwingConstants.CENTER);
            label.setFont(new Font("JetBrains Mono", Font.PLAIN, 24));
            
            JPanel sample = new JPanel();
            sample.setPreferredSize(new Dimension(300, 50));
            sample.setLayout(new GridLayout());
            sample.setOpaque(false);
            
            sample.add(label);
            DueDateColumn.add(sample);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        MainContentSection = new javax.swing.JPanel();
        DueDateColumn = new javax.swing.JPanel();
        DueDateHeading = new javax.swing.JPanel();
        DueDateHeadingText = new javax.swing.JLabel();
        FeeTitleColumn = new javax.swing.JPanel();
        FeeTitleHeading = new javax.swing.JPanel();
        FeeTitleHeadingText = new javax.swing.JLabel();
        AmountColumn = new javax.swing.JPanel();
        AmountHeading = new javax.swing.JPanel();
        AmountHeadingText = new javax.swing.JLabel();
        StatusColumn = new javax.swing.JPanel();
        StatusHeading = new javax.swing.JPanel();
        StatusHeadingText = new javax.swing.JLabel();
        FooterSection = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(1006, 680));

        MainContentSection.setPreferredSize(new java.awt.Dimension(1006, 520));
        MainContentSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        DueDateColumn.setBackground(new java.awt.Color(217, 217, 217));
        DueDateColumn.setPreferredSize(new java.awt.Dimension(300, 720));
        DueDateColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        DueDateHeading.setBackground(new java.awt.Color(205, 205, 205));
        DueDateHeading.setPreferredSize(new java.awt.Dimension(300, 70));
        DueDateHeading.setLayout(new java.awt.GridLayout());

        DueDateHeadingText.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        DueDateHeadingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DueDateHeadingText.setText("Due Date");
        DueDateHeading.add(DueDateHeadingText);

        DueDateColumn.add(DueDateHeading);

        MainContentSection.add(DueDateColumn);

        FeeTitleColumn.setBackground(new java.awt.Color(217, 217, 217));
        FeeTitleColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(205, 205, 205)));
        FeeTitleColumn.setPreferredSize(new java.awt.Dimension(300, 720));
        FeeTitleColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        FeeTitleHeading.setBackground(new java.awt.Color(205, 205, 205));
        FeeTitleHeading.setPreferredSize(new java.awt.Dimension(300, 70));
        FeeTitleHeading.setLayout(new java.awt.GridLayout());

        FeeTitleHeadingText.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        FeeTitleHeadingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FeeTitleHeadingText.setText("Title");
        FeeTitleHeading.add(FeeTitleHeadingText);

        FeeTitleColumn.add(FeeTitleHeading);

        MainContentSection.add(FeeTitleColumn);

        AmountColumn.setBackground(new java.awt.Color(217, 217, 217));
        AmountColumn.setPreferredSize(new java.awt.Dimension(190, 720));
        AmountColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        AmountHeading.setBackground(new java.awt.Color(205, 205, 205));
        AmountHeading.setPreferredSize(new java.awt.Dimension(190, 70));
        AmountHeading.setLayout(new java.awt.GridLayout());

        AmountHeadingText.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        AmountHeadingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmountHeadingText.setText("Amount");
        AmountHeading.add(AmountHeadingText);

        AmountColumn.add(AmountHeading);

        MainContentSection.add(AmountColumn);

        StatusColumn.setBackground(new java.awt.Color(217, 217, 217));
        StatusColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(205, 205, 205)));
        StatusColumn.setPreferredSize(new java.awt.Dimension(216, 720));
        StatusColumn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        StatusHeading.setBackground(new java.awt.Color(205, 205, 205));
        StatusHeading.setPreferredSize(new java.awt.Dimension(216, 70));
        StatusHeading.setLayout(new java.awt.GridLayout());

        StatusHeadingText.setFont(new java.awt.Font("JetBrains Mono", 0, 36)); // NOI18N
        StatusHeadingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusHeadingText.setText("Status");
        StatusHeading.add(StatusHeadingText);

        StatusColumn.add(StatusHeading);

        MainContentSection.add(StatusColumn);

        FooterSection.setBackground(new java.awt.Color(205, 205, 205));
        FooterSection.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(205, 205, 205)));
        FooterSection.setPreferredSize(new java.awt.Dimension(1006, 160));
        FooterSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(503, 200));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        TotalLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        TotalLabel.setText("Total:");
        jPanel3.add(TotalLabel);

        AmountLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        AmountLabel.setText("101023123");
        jPanel3.add(AmountLabel);

        FooterSection.add(jPanel3);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(503, 200));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jButton1.setText("Pay Fees");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 104, 150, 40));

        FooterSection.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(FooterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainContentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FooterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AmountColumn;
    private javax.swing.JPanel AmountHeading;
    private javax.swing.JLabel AmountHeadingText;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JPanel DueDateColumn;
    private javax.swing.JPanel DueDateHeading;
    private javax.swing.JLabel DueDateHeadingText;
    private javax.swing.JPanel FeeTitleColumn;
    private javax.swing.JPanel FeeTitleHeading;
    private javax.swing.JLabel FeeTitleHeadingText;
    private javax.swing.JPanel FooterSection;
    private javax.swing.JPanel MainContentSection;
    private javax.swing.JPanel StatusColumn;
    private javax.swing.JPanel StatusHeading;
    private javax.swing.JLabel StatusHeadingText;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
