/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Jireh
 */
public class PayFeesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayFeesPanel
     */
    public PayFeesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainContentSection = new javax.swing.JPanel();
        HeadingSection = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DueDateColumn = new javax.swing.JPanel();
        FeeTitleColumn = new javax.swing.JPanel();
        AmountColumn = new javax.swing.JPanel();
        StatusColumn = new javax.swing.JPanel();
        FooterSection = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1006, 680));

        MainContentSection.setPreferredSize(new java.awt.Dimension(1006, 520));
        MainContentSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        HeadingSection.setPreferredSize(new java.awt.Dimension(1006, 100));
        HeadingSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel9.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Due Date");
        jPanel9.add(jLabel2);

        HeadingSection.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jPanel10.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Title");
        jPanel10.add(jLabel4);

        HeadingSection.add(jPanel10);

        jPanel8.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Amount");
        jPanel8.add(jLabel5);

        HeadingSection.add(jPanel8);

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel11.setPreferredSize(new java.awt.Dimension(206, 100));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Status");
        jPanel11.add(jLabel6);

        HeadingSection.add(jPanel11);

        MainContentSection.add(HeadingSection);

        DueDateColumn.setPreferredSize(new java.awt.Dimension(250, 620));
        MainContentSection.add(DueDateColumn);

        FeeTitleColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        FeeTitleColumn.setPreferredSize(new java.awt.Dimension(350, 620));
        MainContentSection.add(FeeTitleColumn);

        AmountColumn.setPreferredSize(new java.awt.Dimension(200, 620));
        MainContentSection.add(AmountColumn);

        StatusColumn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 0, 0)));
        StatusColumn.setPreferredSize(new java.awt.Dimension(206, 620));
        MainContentSection.add(StatusColumn);

        FooterSection.setBackground(new java.awt.Color(205, 205, 205));
        FooterSection.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(205, 205, 205)));
        FooterSection.setPreferredSize(new java.awt.Dimension(1006, 160));
        FooterSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(503, 200));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        TotalLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        TotalLabel.setText("Total:");
        jPanel3.add(TotalLabel);

        AmountLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        AmountLabel.setText("101023123");
        jPanel3.add(AmountLabel);

        FooterSection.add(jPanel3);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(503, 200));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jButton1.setText("Pay Fees");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 104, 150, 40));

        FooterSection.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainContentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(FooterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainContentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FooterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AmountColumn;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JPanel DueDateColumn;
    private javax.swing.JPanel FeeTitleColumn;
    private javax.swing.JPanel FooterSection;
    private javax.swing.JPanel HeadingSection;
    private javax.swing.JPanel MainContentSection;
    private javax.swing.JPanel StatusColumn;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
