/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sims.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sims.database.DatabaseConnector;
import sims.model.Student;

/**
 *
 * @author Jireh
 */
public class UserProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserProfilePanel
     * @param student
     */
    public UserProfilePanel(Student student) {
        initComponents();
        initStudentData(student);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        PrimaryInformationSection = new javax.swing.JPanel();
        studentNumberLabel = new javax.swing.JLabel();
        studentNumber = new javax.swing.JLabel();
        institutionalEmailLabel = new javax.swing.JLabel();
        studentInstitutionalEmail = new javax.swing.JLabel();
        FullNameSection = new javax.swing.JPanel();
        firstNameField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        SexSection = new javax.swing.JPanel();
        sexLabel = new javax.swing.JLabel();
        sexComboBox = new javax.swing.JComboBox<>();
        BirthdaySection = new javax.swing.JPanel();
        birthdayLabel = new javax.swing.JLabel();
        birthdayField = new javax.swing.JTextField();
        ContactSection = new javax.swing.JPanel();
        contactNoLabel = new javax.swing.JLabel();
        contactNoField = new javax.swing.JTextField();
        GuardianSection = new javax.swing.JPanel();
        guardianNameLabel = new javax.swing.JLabel();
        guardianNameField = new javax.swing.JTextField();
        PasswordSection = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        AddressSection = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        AltEmailSection = new javax.swing.JPanel();
        altEmailLabel = new javax.swing.JLabel();
        altEmailField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 720));

        saveButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        PrimaryInformationSection.setPreferredSize(new java.awt.Dimension(260, 243));
        PrimaryInformationSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        studentNumberLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        studentNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentNumberLabel.setText("Student Number:");
        studentNumberLabel.setPreferredSize(new java.awt.Dimension(163, 24));
        PrimaryInformationSection.add(studentNumberLabel);

        studentNumber.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        studentNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentNumber.setText("201232132311");
        studentNumber.setInheritsPopupMenu(false);
        studentNumber.setPreferredSize(new java.awt.Dimension(300, 40));
        PrimaryInformationSection.add(studentNumber);

        institutionalEmailLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        institutionalEmailLabel.setText("Institutional Email:");
        PrimaryInformationSection.add(institutionalEmailLabel);

        studentInstitutionalEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        studentInstitutionalEmail.setText("john.smith@cvsu.edu.ph");
        studentInstitutionalEmail.setPreferredSize(new java.awt.Dimension(300, 40));
        PrimaryInformationSection.add(studentInstitutionalEmail);

        FullNameSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        firstNameField.setPreferredSize(new java.awt.Dimension(150, 30));
        FullNameSection.add(firstNameField);

        middleNameField.setPreferredSize(new java.awt.Dimension(150, 30));
        FullNameSection.add(middleNameField);

        lastNameField.setPreferredSize(new java.awt.Dimension(150, 30));
        FullNameSection.add(lastNameField);

        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstNameLabel.setText("First Name");
        firstNameLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        FullNameSection.add(firstNameLabel);

        middleNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        middleNameLabel.setText("Middle Name");
        middleNameLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        FullNameSection.add(middleNameLabel);

        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameLabel.setText("Last Name");
        lastNameLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        FullNameSection.add(lastNameLabel);

        sexLabel.setText("Sex");
        SexSection.add(sexLabel);

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sexComboBox.setPreferredSize(new java.awt.Dimension(120, 30));
        SexSection.add(sexComboBox);

        BirthdaySection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        birthdayLabel.setText("Birthday");
        birthdayLabel.setPreferredSize(new java.awt.Dimension(51, 16));
        BirthdaySection.add(birthdayLabel);

        birthdayField.setText("MM-DD-YEAR");
        birthdayField.setPreferredSize(new java.awt.Dimension(250, 30));
        BirthdaySection.add(birthdayField);

        ContactSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        contactNoLabel.setText("Contact #");
        ContactSection.add(contactNoLabel);

        contactNoField.setPreferredSize(new java.awt.Dimension(250, 30));
        ContactSection.add(contactNoField);

        GuardianSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        guardianNameLabel.setText("Guardian Name");
        GuardianSection.add(guardianNameLabel);

        guardianNameField.setPreferredSize(new java.awt.Dimension(250, 30));
        GuardianSection.add(guardianNameField);

        PasswordSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        passwordLabel.setText("Password");
        passwordLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        PasswordSection.add(passwordLabel);

        passwordField.setPreferredSize(new java.awt.Dimension(250, 30));
        PasswordSection.add(passwordField);

        AddressSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        addressLabel.setText("Address");
        addressLabel.setPreferredSize(new java.awt.Dimension(51, 16));
        AddressSection.add(addressLabel);

        addressField.setPreferredSize(new java.awt.Dimension(750, 30));
        AddressSection.add(addressField);

        AltEmailSection.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        altEmailLabel.setText("Alt Email");
        altEmailLabel.setPreferredSize(new java.awt.Dimension(51, 16));
        AltEmailSection.add(altEmailLabel);

        altEmailField.setPreferredSize(new java.awt.Dimension(250, 30));
        AltEmailSection.add(altEmailField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrimaryInformationSection, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BirthdaySection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardianSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FullNameSection, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SexSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AltEmailSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PrimaryInformationSection, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FullNameSection, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardianSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdaySection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AltEmailSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(AddressSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initStudentData (Student student) {
        try(var conn = DatabaseConnector.getConnection()){
            String selectStudentQuery = "SELECT * FROM student INNER JOIN student_info on student.id = student_info.studentId WHERE studentNumber = %s".formatted(student.getStudentNumber());
            var stmt = conn.createStatement();
            var studentResultSet = stmt.executeQuery(selectStudentQuery);
            
            // if there are no results returned
            if (!studentResultSet.isBeforeFirst()) {
                Modal.show("No student found!", "Notice", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            while(studentResultSet.next()) {
                //======================================================================
                // NULLABLE COLUMNS
                //======================================================================                
                if (studentResultSet.getString("middleName") != null) middleNameField.setText(studentResultSet.getString("middleName"));
                if (studentResultSet.getString("sex") != null) sexComboBox.setSelectedItem(studentResultSet.getString("sex"));
                if (studentResultSet.getString("contactNumber") != null) contactNoField.setText(studentResultSet.getString("contactNumber"));
                if (studentResultSet.getString("birthday") != null) birthdayField.setText(studentResultSet.getString("birthday"));
                if (studentResultSet.getString("guardianName") != null) guardianNameField.setText(studentResultSet.getString("guardianName"));
                if (studentResultSet.getString("alternativeEmail") != null) altEmailField.setText(studentResultSet.getString("alternativeEmail"));
                if (studentResultSet.getString("address") != null) addressField.setText(studentResultSet.getString("address"));
                
                studentNumber.setText(studentResultSet.getString("studentNumber"));
                studentInstitutionalEmail.setText(studentResultSet.getString("email"));
                firstNameField.setText(studentResultSet.getString("firstName"));
                passwordField.setText(studentResultSet.getString("password"));
                lastNameField.setText(studentResultSet.getString("lastName"));
            }
            
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(UserProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressSection;
    private javax.swing.JPanel AltEmailSection;
    private javax.swing.JPanel BirthdaySection;
    private javax.swing.JPanel ContactSection;
    private javax.swing.JPanel FullNameSection;
    private javax.swing.JPanel GuardianSection;
    private javax.swing.JPanel PasswordSection;
    private javax.swing.JPanel PrimaryInformationSection;
    private javax.swing.JPanel SexSection;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField altEmailField;
    private javax.swing.JLabel altEmailLabel;
    private javax.swing.JTextField birthdayField;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField contactNoField;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField guardianNameField;
    private javax.swing.JLabel guardianNameLabel;
    private javax.swing.JLabel institutionalEmailLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel studentInstitutionalEmail;
    private javax.swing.JLabel studentNumber;
    private javax.swing.JLabel studentNumberLabel;
    // End of variables declaration//GEN-END:variables
}
